= Number Six, 64oz. Version

I use a Vitamix, because it is awesome, and because I make this a lot. The
sauce will be different with a regular blender, but still great. This
recipe fills the giant Vitamix jar to the very top top with sauce. If you
don't have a 64oz jar, you will need to scale this down.

== The Liquid

TIP: This isn't always exact, but it is a 2/1 mixture of water and apple cider vinegar. For
reasons I don't understand, sometimes I need more sometimes I need less.

Bring to a boil

* 6 cups water

Turn the heat off, add

* 3 cups apple cider vinegar

Set aside.

== The Seed Roasting

TIP: You can do this any way that works for you, but I get the best results
from putting the objects to be toasted in a the bottom of a roasting pan, the
kind that has rounded corners, and then setting it under the broiler on high heat,
and pulling it out to shake the seeds to even out the roasting every few seconds.

* Roast 1 cup pumpkin seeds - slightly dark, don't let any seeds go black
* Roast 1/2 cup sesame seeds -- nice round medium brown

Set the seeds aside.

== The Chili Peppers

WARNING: I buy Arbol chilis with the stems off. If you end up having to
de-stem an entire batch of chilis, do it in a place where there is good ventilation,
because the chili dust can do a number on you if you aren't careful.

Place in your blender:

* 65 g Arbol ( will have seeds, it is too much work to take them out )
* 65 g Guajillo ( Remove stems and seeds )

Blend until you have a very fine chili powder.

== Making The Sauce

Next, add all the dry ingredients to the chili powder:

* The roasted seeds
* 16 large allspice berries ( 2.2 g )
* 18 cloves
* 1 T cumin seeds
* 4 tsp Mexican oregano
* 3 T dried roasted garlic flakes
* 1 T salt
* 6 T cocoa nibs

Now adding just enough of the liquid to keep it blending,
blend this into something which looks like peanut butter.
Get it as smooth as you can.

Add remaining liquid to blender, and spin it into sauce.

WARNING: You are about to take the lid off the blender, don't
stick your face in the fumes that come out, this has proven
to be a bad idea.

This will "fill" more than 12 and less than 16 five-ounce bottles
depending on how full you make them.
